plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
      tests_patterns:
        - src/test/**
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"